#!/bin/bash
#
# Author:
#   Felix Hanke <idontliketosharemy@email.com>
#
# Description:
#   This script will remove a series of packages in order to obtain a minimal Linux Mint Cinnamon 21.1.
#
# Legislative Preamble:
#   Bla bla bla
#
# Usage:
#   1. chmod +x mint_minimal.sh
#   2. sudo ./mint_minimal.sh
#
# In case of "Not able to execute a .sh file: /bin/bash^M: bad interpreter", use:
#   sed -i -e 's/\r$//' <ScriptName.sh>
#
echo "Clear screen..."
clear
#
echo "Removing packages..." 
apt purge --ignore-missing \
baobab \
bison \
celluloid \
dc \
drawing \
fonts-opensymbol \
gir1.2-rb-3.0 \
gir1.2-xviewer-3.0 \
gnome-calculator \
gnome-calendar \
gnome-disk-utility \
gnome-font-viewer \
gnome-screenshot \
gucharmap \
hexchat \
hunspell \
hunspell-af \
hunspell-an \
hunspell-ar \
hunspell-be \
hunspell-bg \
hunspell-bn \
hunspell-bo \
hunspell-br \
hunspell-bs \
hunspell-ca \
hunspell-cs \
hunspell-da \
hunspell-de-at \
hunspell-de-at-frami \
hunspell-de-at-frami \
hunspell-de-at-frami \
hunspell-de-at-frami \
hunspell-de-ch \
hunspell-de-ch-frami \
hunspell-de-ch-frami \
hunspell-de-ch-frami \
hunspell-de-ch-frami \
hunspell-de-de \
hunspell-de-de-frami \
hunspell-de-de-frami \
hunspell-de-de-frami \
hunspell-de-de-frami \
hunspell-de-med \
hunspell-dz \
hunspell-el \
hunspell-en-au \
hunspell-en-au \
hunspell-en-au \
hunspell-en-ca \
hunspell-en-ca \
hunspell-en-ca \
hunspell-en-gb \
hunspell-en-gb \
hunspell-en-gb \
hunspell-en-med \
hunspell-en-us \
hunspell-en-us \
hunspell-en-za \
hunspell-en-za \
hunspell-en-za \
hunspell-es \
hunspell-es \
hunspell-es \
hunspell-eu \
hunspell-fr \
hunspell-fr \
hunspell-fr-classical \
hunspell-fr-classical \
hunspell-fr-classical \
hunspell-fr-comprehensive \
hunspell-gd \
hunspell-gl \
hunspell-gl-es \
hunspell-gu \
hunspell-gug \
hunspell-he \
hunspell-hi \
hunspell-hr \
hunspell-hu \
hunspell-id \
hunspell-is \
hunspell-it \
hunspell-it \
hunspell-it \
hunspell-kk \
hunspell-kmr \
hunspell-ko \
hunspell-lo \
hunspell-lt \
hunspell-lv \
hunspell-ml \
hunspell-mn \
hunspell-ne \
hunspell-nl \
hunspell-no \
hunspell-oc \
hunspell-pl \
hunspell-pt-br \
hunspell-pt-br \
hunspell-pt-br \
hunspell-pt-pt \
hunspell-pt-pt \
hunspell-pt-pt \
hunspell-ro \
hunspell-ru \
hunspell-ru \
hunspell-ru \
hunspell-si \
hunspell-sk \
hunspell-sl \
hunspell-sr \
hunspell-sv \
hunspell-sv-se \
hunspell-sw \
hunspell-te \
hunspell-th \
hunspell-tools \
hunspell-tr \
hunspell-uk \
hunspell-uz \
hunspell-vi \
hyphen-af \
hyphen-as \
hyphen-bg \
hyphen-bn \
hyphen-ca \
hyphen-cs \
hyphen-da \
hyphen-de \
hyphen-de \
hyphen-de \
hyphen-el \
hyphen-en-ca \
hyphen-en-ca \
hyphen-en-gb \
hyphen-en-gb \
hyphen-en-gb \
hyphen-en-us \
hyphen-en-us \
hyphen-en-us \
hyphen-es \
hyphen-fi \
hyphen-fr \
hyphen-fr \
hyphen-fr \
hyphen-ga \
hyphen-gl \
hyphen-gu \
hyphen-hi \
hyphen-hr \
hyphen-hr \
hyphen-hu \
hyphen-id \
hyphen-is \
hyphen-it \
hyphen-it \
hyphen-it \
hyphen-kn \
hyphen-lt \
hyphen-lv \
hyphen-ml \
hyphen-mn \
hyphen-mr \
hyphen-nl \
hyphen-no \
hyphen-or \
hyphen-pa \
hyphen-pl \
hyphen-pl \
hyphen-pt-br \
hyphen-pt-br \
hyphen-pt-br \
hyphen-pt-pt \
hyphen-pt-pt \
hyphen-pt-pt \
hyphen-ro \
hyphen-ru \
hyphen-ru \
hyphen-ru \
hyphen-show \
hyphen-sk \
hyphen-sl \
hyphen-sr \
hyphen-sv \
hyphen-ta \
hyphen-te \
hyphen-uk \
hyphen-zu \
hypnotix \
liblibreoffice-java \
libmythes-1.2-0 \
libreoffice-base \
libreoffice-base-core \
libreoffice-base-drivers \
libreoffice-calc \
libreoffice-common \
libreoffice-core \
libreoffice-draw \
libreoffice-gnome \
libreoffice-gtk3 \
libreoffice-help-common \
libreoffice-help-de \
libreoffice-help-de \
libreoffice-help-en-gb \
libreoffice-help-en-gb \
libreoffice-help-en-us \
libreoffice-help-en-us \
libreoffice-help-es \
libreoffice-help-es \
libreoffice-help-fr \
libreoffice-help-fr \
libreoffice-help-it \
libreoffice-help-it \
libreoffice-help-pt \
libreoffice-help-pt \
libreoffice-help-pt-br \
libreoffice-help-pt-br \
libreoffice-help-ru \
libreoffice-help-ru \
libreoffice-help-zh-cn \
libreoffice-help-zh-cn \
libreoffice-help-zh-tw \
libreoffice-help-zh-tw \
libreoffice-impress \
libreoffice-java-common \
libreoffice-l10n-de \
libreoffice-l10n-de \
libreoffice-l10n-en-gb \
libreoffice-l10n-en-gb \
libreoffice-l10n-en-za \
libreoffice-l10n-en-za \
libreoffice-l10n-es \
libreoffice-l10n-es \
libreoffice-l10n-fr \
libreoffice-l10n-fr \
libreoffice-l10n-it \
libreoffice-l10n-it \
libreoffice-l10n-pt \
libreoffice-l10n-pt \
libreoffice-l10n-pt-br \
libreoffice-l10n-pt-br \
libreoffice-l10n-ru \
libreoffice-l10n-ru \
libreoffice-l10n-zh-cn \
libreoffice-l10n-zh-cn \
libreoffice-l10n-zh-tw \
libreoffice-l10n-zh-tw \
libreoffice-math \
libreoffice-sdbc-hsqldb \
libreoffice-style-colibre \
libreoffice-writer \
librhythmbox-core10 \
libsort-versions-perl \
libuno-cppu3 \
libuno-cppuhelpergcc3-3 \
libunoloader-java \
libuno-purpenvhelpergcc3-3 \
libuno-sal3 \
libuno-salhelpergcc3-3 \
mintstick \
mythes-de \
mythes-de \
mythes-de-ch \
mythes-de-ch \
mythes-en-au \
mythes-en-us \
mythes-en-us \
mythes-fr \
mythes-fr \
mythes-it \
mythes-it \
mythes-pt-pt \
mythes-pt-pt \
mythes-ru \
onboard \
pix \
pix-dbg \
python3-uno \
redshift-gtk \
rhythmbox \
rhythmbox-data \
rhythmbox-plugins \
rhythmbox-plugin-tray-icon \
seahorse \
simple-scan \
sticky \
thunderbird \
thunderbird-gnome-support \
thunderbird-locale-de \
thunderbird-locale-en \
thunderbird-locale-en \
thunderbird-locale-en-gb \
thunderbird-locale-en-us \
thunderbird-locale-en-us \
thunderbird-locale-es \
thunderbird-locale-es-ar \
thunderbird-locale-es-es \
thunderbird-locale-fr \
thunderbird-locale-fr \
thunderbird-locale-it \
thunderbird-locale-pt \
thunderbird-locale-pt-br \
thunderbird-locale-pt-pt \
thunderbird-locale-ru \
thunderbird-locale-zh-cn \
thunderbird-locale-zh-hans \
thunderbird-locale-zh-hant \
thunderbird-locale-zh-tw \
transmission-gtk \
uno-libs-private \
ure \
ure-java \
warpinator \
webapp-manager \
xed \
xed-dbg \
xreader \
xreader-dbg \
xviewer \
xviewer-dbg \
xviewer-plugins \
apg                             \
aspell                          \
aspell-en                       \
bolt                            \
breeze-cursor-theme             \
breeze-icon-theme               \
brltty                          \
busybox-initramfs               \
busybox-static                  \
blt                             \
blueman                         \
bluetooth                       \
bluez                           \
bluez-cups                      \
caribou                         \
casper                          \
catfish                         \
cryptsetup                      \
cryptsetup-bin                  \
cryptsetup-initramfs            \
cups                            \
cups-browsed                    \
cups-bsd                        \
cups-client                     \
cups-common                     \
cups-core-drivers               \
cups-daemon                     \
cups-filters                    \
cups-filters-core-drivers       \
cups-ipp-utils                  \
cups-pk-helper                  \
cups-ppdc                       \
cups-server-common              \
dcraw                           \
default-jre                     \
default-jre-headless            \
diffstat                        \
dmz-cursor-theme                \
doc-base                        \
docbook-xml                     \
ecryptfs-utils                  \
enchant-2                       \
ffmpegthumbnailer               \
firefox                         \
firefox-locale-en               \
fonts-beng                      \
fonts-beng-extra                \
fonts-dejavu-core               \
fonts-deva                      \
fonts-deva-extra                \
fonts-droid-fallback            \
fonts-freefont-ttf              \
fonts-gargi                     \
fonts-gubbi                     \
fonts-gujr                      \
fonts-gujr-extra                \
fonts-guru                      \
fonts-guru-extra                \
fonts-indic                     \
fonts-kacst                     \
fonts-kacst-one                 \
fonts-kalapi                    \
fonts-khmeros-core              \
fonts-knda                      \
fonts-lao                       \
fonts-liberation                \
fonts-liberation2               \
fonts-lklug-sinhala             \
fonts-lohit-beng-assamese       \
fonts-lohit-beng-bengali        \
fonts-lohit-deva                \
fonts-lohit-gujr                \
fonts-lohit-guru                \
fonts-lohit-knda                \
fonts-lohit-mlym                \
fonts-lohit-orya                \
fonts-lohit-taml                \
fonts-lohit-taml-classical      \
fonts-lohit-telu                \
fonts-mathjax                   \
fonts-mlym                      \
fonts-nakula                    \
fonts-navilu                    \
fonts-noto-cjk                  \
fonts-noto-color-emoji          \
fonts-noto-mono                 \
fonts-orya                      \
fonts-orya-extra                \
fonts-pagul                     \
fonts-sahadeva                  \
fonts-samyak-deva               \
fonts-samyak-gujr               \
fonts-samyak-mlym               \
fonts-samyak-taml               \
fonts-sarai                     \
fonts-sil-abyssinica            \
fonts-sil-padauk                \
fonts-smc                       \
fonts-smc-anjalioldlipi         \
fonts-smc-chilanka              \
fonts-smc-dyuthi                \
fonts-smc-gayathri              \
fonts-smc-karumbi               \
fonts-smc-keraleeyam            \
fonts-smc-manjari               \
fonts-smc-meera                 \
fonts-smc-rachana               \
fonts-smc-raghumalayalamsans    \
fonts-smc-suruma                \
fonts-smc-uroob                 \
fonts-taml                      \
fonts-telu                      \
fonts-telu-extra                \
fonts-teluguvijayam             \
fonts-thai-tlwg                 \
fonts-tibetan-machine           \
fonts-tlwg-garuda               \
fonts-tlwg-garuda-ttf           \
fonts-tlwg-kinnari              \
fonts-tlwg-kinnari-ttf          \
fonts-tlwg-laksaman             \
fonts-tlwg-laksaman-ttf         \
fonts-tlwg-loma                 \
fonts-tlwg-loma-ttf             \
fonts-tlwg-mono                 \
fonts-tlwg-mono-ttf             \
fonts-tlwg-norasi               \
fonts-tlwg-norasi-ttf           \
fonts-tlwg-purisa               \
fonts-tlwg-purisa-ttf           \
fonts-tlwg-sawasdee             \
fonts-tlwg-sawasdee-ttf         \
fonts-tlwg-typewriter           \
fonts-tlwg-typewriter-ttf       \
fonts-tlwg-typist               \
fonts-tlwg-typist-ttf           \
fonts-tlwg-typo                 \
fonts-tlwg-typo-ttf             \
fonts-tlwg-umpush               \
fonts-tlwg-umpush-ttf           \
fonts-tlwg-waree                \
fonts-tlwg-waree-ttf            \
fonts-urw-base35                \
fonts-yrsa-rasa                 \
foomatic-db-compressed-ppds     \
fprintd                         \
friendly-recovery               \
gamemode                        \
gamemode-daemon                 \
gawk                            \
gcc                             \
gcr                             \
genisoimage                     \
geoclue-2.0                     \
ghostscript                     \
ghostscript-x                   \
gir1.2-accountsservice-1.0      \
gir1.2-atspi-2.0                \
gir1.2-ayatanaappindicator3-0.1 \
gir1.2-caribou-1.0              \
gir1.2-clutter-1.0              \
gir1.2-cogl-1.0                 \
gir1.2-dbusmenu-glib-0.4        \
gir1.2-dee-1.0                  \
gir1.2-flatpak-1.0              \
gir1.2-gspell-1                 \
gir1.2-gst-plugins-base-1.0     \
gir1.2-gstreamer-1.0            \
gir1.2-gtksource-3.0            \
gir1.2-gtksource-4              \
gir1.2-gtop-2.0                 \
gir1.2-gudev-1.0                \
gir1.2-handy-1                  \
gir1.2-ibus-1.0                 \
gir1.2-javascriptcoregtk-4.0    \
gir1.2-json-1.0                 \
gir1.2-nm-1.0                   \
gir1.2-nma-1.0                  \
gir1.2-peas-1.0                 \
gir1.2-polkit-1.0               \
gir1.2-secret-1                 \
gir1.2-soup-2.4                 \
gir1.2-timezonemap-1.0          \
gir1.2-udisks-2.0               \
gir1.2-upowerglib-1.0           \
gir1.2-webkit2-4.0              \
gir1.2-wnck-3.0                 \
gir1.2-xfconf-0                 \
gir1.2-xkl-1.0                  \
gnome-accessibility-themes      \
gnome-keyring                   \
gnome-keyring-pkcs11            \
gnome-themes-extra              \
gnome-themes-extra-data         \
growisofs                       \
gsfonts                         \
gstreamer1.0-alsa               \
gstreamer1.0-clutter-3.0        \
gstreamer1.0-gl                 \
gstreamer1.0-gtk3               \
gstreamer1.0-packagekit         \
gstreamer1.0-pipewire           \
gstreamer1.0-plugins-base-apps  \
gstreamer1.0-pulseaudio         \
gstreamer1.0-tools              \
gstreamer1.0-x                  \
hexchat-common                  \
hplip                           \
hplip-data                      \
libtk8.6                        \
ideviceinstaller                \
iw                              \
java-common                     \
laptop-detect                   \
linux-sound-base                \
lvm2                            \
mailcap                         \
media-player-info               \
mint-backgrounds-vanessa        \
mintbackup                      \
mintupdate                      \
mintwelcome                     \
mobile-broadband-provider-info  \
numix-icon-theme                \
numix-icon-theme-circle         \
nvidia-prime-applet             \
onboard-common                  \
openjdk-11-jre                  \
openjdk-11-jre-headless         \
openprinting-ppds               \
openssh-client                  \
openvpn                         \
orca                            \
papirus-icon-theme              \
pavucontrol                     \
pipewire                        \
pipewire-bin                    \
pix-data                        \
poppler-data                    \
poppler-utils                   \
printer-driver-brlaser          \
printer-driver-c2esp            \
printer-driver-foo2zjs-common   \
printer-driver-gutenprint       \
printer-driver-hpcups           \
printer-driver-m2300w           \
printer-driver-min12xxw         \
printer-driver-pnm2ppa          \
printer-driver-postscript-hp    \
printer-driver-ptouch           \
printer-driver-pxljr            \
printer-driver-sag-gdi          \
printer-driver-splix            \
pulseaudio                      \
pulseaudio-module-bluetooth     \
pulseaudio-utils                \
python3-blinker                 \
python3-brlapi                  \
python3-bs4                     \
python3-cffi-backend            \
python3-click                   \
python3-colorama                \
python3-commandnotfound         \
python3-compizconfig            \
python3-configobj               \
python3-cryptography            \
python3-cups                    \
python3-cupshelpers             \
python3-distro                  \
python3-eyed3                   \
python3-filelock                \
python3-gdbm                    \
python3-gnupg                   \
python3-grpcio                  \
python3-httplib2                \
python3-icu                     \
python3-ifaddr                  \
python3-imdbpy                  \
python3-importlib-metadata      \
python3-jeepney                 \
python3-jwt                     \
python3-keyring                 \
python3-launchpadlib            \
python3-lazr.restfulclient      \
python3-lazr.uri                \
python3-ldb                     \
python3-louis                   \
python3-magic                   \
python3-mako                    \
python3-markupsafe              \
python3-more-itertools          \
python3-nacl                    \
python3-netaddr                 \
python3-oauthlib                \
python3-packaging               \
python3-parted                  \
python3-pexpect                 \
python3-pil                     \
python3-problem-report          \
python3-protobuf                \
python3-ptyprocess              \
python3-pyatspi                 \
python3-pyelftools              \
python3-pyparsing               \
python3-reportlab               \
python3-reportlab-accel         \
python3-requests-file           \
python3-samba                   \
python3-secretstorage           \
python3-soupsieve               \
python3-speechd                 \
python3-systemd                 \
python3-talloc                  \
python3-tdb                     \
python3-tldextract              \
python3-unidecode               \
python3-wadllib                 \
python3-xdg                     \
python3-xkit                    \
python3-zipp                    \
qt5-gtk-platformtheme           \
qt5-gtk2-platformtheme          \
qt5-style-plugin-cleanlooks     \
qt5-style-plugin-motif          \
qt5-style-plugin-plastique      \
qt5-style-plugins               \
qt5ct                           \
qttranslations5-l10n            \
samba-common                    \
samba-common-bin                \
samba-libs                      \
sane-airscan                    \
sane-utils                      \
sound-theme-freedesktop         \
speech-dispatcher               \
speech-dispatcher-audio-plugins \
speech-dispatcher-espeak-ng     \
tcl                             \
tcl8.6                          \
telnet                          \
timeshift                       \
tnftp                           \
transmission-common             \
wamerican                       \
wbrazilian                      \
wbritish                        \
wfrench                         \
wireless-regdb                  \
wireless-tools                  \
witalian                        \
wngerman                        \
wogerman                        \
wpasupplicant                   \
wportuguese                     \
wspanish                        \
wswiss                          \
xapp-appimage-thumbnailer       \
xapp-epub-thumbnailer           \
xapp-mp3-thumbnailer            \
xapp-raw-thumbnailer            \
xapp-thumbnailers-common        \
xfce4-appfinder                 \
xfce4-dict                      \
xfce4-eyes-plugin               \
xfce4-mailwatch-plugin          \
xfce4-pulseaudio-plugin         \
xfce4-screenshooter             \
xfce4-volumed                   \
xfce4-weather-plugin            \
xfce4-xapp-status-plugin        \
xfce4-notifyd                   \
xfce4-statusnotifier-plugin     \
xfce4-time-out-plugin           \
xfce4-timer-plugin              \
xreader-common                  \
yaru-theme-icon                 \
youtube-dl                      \
xfce4-taskmanager               \
file-roller                     \
xfce4-power-manager-data        \
xfce4-power-manager             \
xfce4-power-manager-plugins     \
xfce4-power-manager             \
synaptic                        \
xfce4-places-plugin             \
xfce4-datetime-plugin



#
echo "cleaning up..."
apt autoremove
rm -rf /usr/share/dict
rm -rf /var/lib/libreoffice
rm -rf /usr/share/fonts/truetype\libreoffice